import fs from 'node:fs/promises';

const CONTENT_EXPORTS = [
  'navigationLinks',
  'heroContent',
  'overviewContent',
  'solutionsContent',
  'caseStudiesContent',
  'aiToolsContent',
  'productShowcaseContent',
  'leadersContent',
  'ctaContent',
  'footerContent',
] as const;

export async function writeContentBarrel(filePath: string): Promise<void> {
  const lines = [
    '// Generated by @poc-microsite/content-utils — do not edit by hand',
    "import content from './landing-page.content.json';",
    '',
    ...CONTENT_EXPORTS.map((name) => `export const ${name} = content.${name};`),
    '',
  ];
  await fs.writeFile(filePath, lines.join('\n'), 'utf8');
}

export async function writeImagesBarrel(filePath: string): Promise<void> {
  const lines = [
    '// Generated by @poc-microsite/content-utils — do not edit by hand',
    "import imagePaths from './images.config.json';",
    '',
    'export const images = imagePaths;',
    '',
  ];
  await fs.writeFile(filePath, lines.join('\n'), 'utf8');
}
