// Generated by @poc-microsite/content-utils — do not edit by hand
import content from './landing-page.content.json';

export const navigationLinks = content.navigationLinks;
export const heroContent = content.heroContent;
export const overviewContent = content.overviewContent;
export const solutionsContent = content.solutionsContent;
export const caseStudiesContent = content.caseStudiesContent;
export const aiToolsContent = content.aiToolsContent;
export const productShowcaseContent = content.productShowcaseContent;
export const leadersContent = content.leadersContent;
export const ctaContent = content.ctaContent;
export const footerContent = content.footerContent;
